# Generated by Django 3.1.3 on 2020-12-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='crate_at',
            new_name='crated_at',
        ),
    ]
