# Generated by Django 3.1.3 on 2020-12-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20201203_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
